#!/usr/bin/env -S bash -eu
pid=0

bye() {
    # Remove bluetooth support
    echo $pid
    kill -TERM $pid
    
    while :;
    do
        if ! pgrep -x rtbth 
        then
            break
        fi

        sleep 0.5
    done

    modprobe -r rtbth
}

# Starts bluetooth device
if command -v systemctl >/dev/null
then
    if ! systemctl is-active bluetooth
    then
        systemctl start bluetooth
    fi
fi

trap bye EXIT

# Load bluetooth mkodule
modprobe -r rtbth || true
modprobe rtbth

# Load bluetooth firmware
/opt/ralink/rtbt &
pid=$!

# Make realtime!
chrt -d -p $pid
renice -n -20 -p $pid
wait
